---
- hosts: workers
  become: yes
  tasks:
    - name: Rebooting ...
      shell: "sleep 3 && reboot"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for rebooted servers to come back
      reboot:
        reboot_timeout: 300
    - debug: var=results.changed 