---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: reset cluster
      shell: kubeadm reset --force
      ignore_errors: true

    - name: reset iptables
      shell: >
        'iptables -F'  
        'iptables -t nat -F' 
        'iptables -t mangle -F' 
        'iptables -X'
          
    - name: restart daemon and docker
      systemd:
        daemon_reload: yes
        name: docker
        state: restarted
  vars_prompt:
    name: "reset_confirmation"
    prompt: "Are you sure you want to reset cluster state? Type 'yes' to reset your cluster."
    default: "no"



#- name: Reset iptables to blank slate
#      command: "{{item}}"
#      with_items:
#        - 'iptables -F'
#        - 'iptables -t nat -F'
#        - 'iptables -t mangle -F'
#        - 'iptables -X'
   