- hosts: workers
  become: yes
  become_method: sudo
  tasks:
    vars_prompt:
    name: "reset_confirmation"
    prompt: "Are you sure you want to reset cluster state? Type 'yes' to reset your cluster."
    default: "no"
  tasks:  
    - name: reset cluster
      shell: "kubeadm reset --force"
      ignore_errors: true

