---
- hosts: workers
  become: yes
  become_method: sudo
  tasks:
    - name: reset cluster
      shell: "kubeadm reset --force"
      ignore_errors: true
  vars_prompt:
    name: "reset_confirmation"
    prompt: "Are you sure you want to reset cluster state? Type 'yes' to reset your cluster."
    default: "no"

- hosts: workers
  become: yes
  tasks:
    - name: reset iptables
      shell: |
        iptables -F  
        #iptables -t nat -F 
        #iptables -t mangle -F 
        #iptables -X"
      register: result  
    - debug: var=results.changed

    - name: restart docker
      systemd:
        name: docker
        state: restarted