---
- hosts: workers
  become: yes
  become_method: sudo
  tasks:
    - name: reset cluster
      shell: kubeadm reset --force
      ignore_errors: true
      register: stdout
    - debug: 
        msg: stdout 

    - name: iptables flush filter
      iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: iptables flush nat
      iptables:
        table: nat
        chain: '{{ item }}'
        flush: yes
      with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]     
    
    - name: restart daemon and docker
      systemd:
        daemon_reload: yes
        name: docker
        state: restarted
  vars_prompt:
    name: "reset_confirmation"
    prompt: "Are you sure you want to reset cluster state? Type 'yes' to reset your cluster."
    default: "no"



   